#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

feh --no-fehbg --bg-fill ~/Wallpapers/kali-green/green-kali16x9.jpg &
~/.config/polybar/./launch.sh &
picom --config ~/.config/picom/picom.conf &

wmname LG3D &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           8
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config border_width 1
bspc config window_gap 8
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
bspc config normal_border_color '#1f1f1f'
bspc config focused_border_color '#168105'
bspc config presel_feedback_color '#46a418'


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

